// <auto-generated />
using System;
using DndEngine.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndEngine.Infrastructure.Migrations.Campaign
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DndEngine.Infrastructure.CampaignRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SrdVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Characters", t =>
                        {
                            t.HasCheckConstraint("CK_Character_Level", "Level BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Character_Revision", "Revision >= 0");
                        });
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatMembershipRow", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("EncounterId");

                    b.ToTable("CombatMemberships");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatProfileRow", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("CombatProfiles");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EventRow", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CharacterRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SrdVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("CampaignId", "Sequence");

                    b.HasIndex("CharacterId", "CharacterRevision")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.ProgressionRow", b =>
                {
                    b.Property<Guid>("CharacterId").HasColumnType("TEXT");
                    b.Property<string>("StateJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("CharacterId");
                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatMembershipRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DndEngine.Infrastructure.EncounterRow", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatProfileRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EventRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DndEngine.Infrastructure.ProgressionRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null).WithMany()
                        .HasForeignKey("CharacterId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
