// <auto-generated />
using System;
using DndEngine.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndEngine.Infrastructure.Migrations.Campaign
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DndEngine.Infrastructure.CampaignRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GameSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SrdVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Characters", t =>
                        {
                            t.HasCheckConstraint("CK_Character_Level", "Level BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Character_Revision", "Revision >= 0");
                        });
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatMembershipRow", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("EncounterId");

                    b.ToTable("CombatMemberships");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatProfileRow", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("CombatProfiles");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EventRow", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CharacterRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SrdVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("CampaignId", "Sequence");

                    b.HasIndex("CharacterId", "CharacterRevision")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.IdempotencyOperationRow", b =>
                {
                    b.Property<Guid>("OperationId").HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("CompletedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("ContentType").HasColumnType("TEXT");
                    b.Property<string>("Location").HasColumnType("TEXT");
                    b.Property<string>("RequestHash").IsRequired().HasColumnType("TEXT");
                    b.Property<byte[]>("ResponseBody").IsRequired().HasColumnType("BLOB");
                    b.Property<int>("StatusCode").HasColumnType("INTEGER");
                    b.HasKey("OperationId");
                    b.ToTable("IdempotencyOperations");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRewardRow", b =>
                {
                    b.Property<Guid>("EncounterId").HasColumnType("TEXT");
                    b.Property<string>("Outcome").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("AvailableExperience").HasColumnType("INTEGER");
                    b.Property<string>("AwardsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DefeatedMonsterIdsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("Revision").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("EncounterId");
                    b.ToTable("EncounterRewards");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.DroppedItemRow", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("TEXT");
                    b.Property<Guid>("CampaignId").HasColumnType("TEXT");
                    b.Property<Guid>("SourceOwnerId").HasColumnType("TEXT");
                    b.Property<string>("DefinitionId").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CampaignId");
                    b.ToTable("DroppedItems");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.InventoryStateRow", b =>
                {
                    b.Property<Guid>("OwnerId").HasColumnType("TEXT");
                    b.Property<string>("ItemsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("CopperPieces").HasColumnType("INTEGER");
                    b.HasKey("OwnerId");
                    b.ToTable("InventoryStates");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.MonsterInstanceRow", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("TEXT");
                    b.Property<Guid>("CampaignId").HasColumnType("TEXT");
                    b.Property<string>("DefinitionId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PackVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SpellPackVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("LimitedUsesJson").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("Revision").IsConcurrencyToken().HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("CampaignId");
                    b.ToTable("MonsterInstances");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.ProgressionRow", b =>
                {
                    b.Property<Guid>("CharacterId").HasColumnType("TEXT");
                    b.Property<string>("StateJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("CharacterId");
                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatMembershipRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DndEngine.Infrastructure.EncounterRow", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatProfileRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EventRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DndEngine.Infrastructure.InventoryStateRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null).WithMany()
                        .HasForeignKey("OwnerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterRewardRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.EncounterRow", null).WithMany()
                        .HasForeignKey("EncounterId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.DroppedItemRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null).WithMany()
                        .HasForeignKey("CampaignId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.MonsterInstanceRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null).WithMany()
                        .HasForeignKey("Id").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("DndEngine.Infrastructure.CampaignRow", null).WithMany()
                        .HasForeignKey("CampaignId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.ProgressionRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.CharacterRow", null).WithMany()
                        .HasForeignKey("CharacterId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
