// <auto-generated />
using DndEngine.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndEngine.Infrastructure.Migrations.Rules
{
    [DbContext(typeof(RulesDbContext))]
    partial class RulesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DndEngine.Infrastructure.CombatContentRow", b =>
                {
                    b.Property<string>("RulesetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RulesetId", "Version");

                    b.ToTable("CombatContent");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterContentRow", b =>
                {
                    b.Property<string>("RulesetId").HasColumnType("TEXT");
                    b.Property<string>("Version").HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DataJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("RulesetId", "Version");
                    b.ToTable("CharacterContent");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.MonsterPackRow", b =>
                {
                    b.Property<string>("RulesetId").HasColumnType("TEXT");
                    b.Property<string>("RulesetVersion").HasColumnType("TEXT");
                    b.Property<string>("PackVersion").HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DataJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("RulesetId", "RulesetVersion", "PackVersion");
                    b.ToTable("MonsterPacks");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterItemPackRow", b =>
                {
                    b.Property<string>("RulesetId").HasColumnType("TEXT");
                    b.Property<string>("RulesetVersion").HasColumnType("TEXT");
                    b.Property<string>("PackVersion").HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DataJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("RulesetId", "RulesetVersion", "PackVersion");
                    b.ToTable("EncounterItemPacks");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SpellContentRow", b =>
                {
                    b.Property<string>("RulesetId").HasColumnType("TEXT");
                    b.Property<string>("Version").HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DataJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("RulesetId", "Version");
                    b.ToTable("SpellContent");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SpellPackRow", b =>
                {
                    b.Property<string>("RulesetId").HasColumnType("TEXT");
                    b.Property<string>("RulesetVersion").HasColumnType("TEXT");
                    b.Property<string>("PackVersion").HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DataJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("RulesetId", "RulesetVersion", "PackVersion");
                    b.ToTable("SpellPacks");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.RulesetRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Version");

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SkillRow", b =>
                {
                    b.Property<string>("RulesetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RulesetId", "Version", "Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CombatContentRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null)
                        .WithMany()
                        .HasForeignKey("RulesetId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.CharacterContentRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null).WithMany()
                        .HasForeignKey("RulesetId", "Version").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.MonsterPackRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null).WithMany()
                        .HasForeignKey("RulesetId", "RulesetVersion").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.EncounterItemPackRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null).WithMany()
                        .HasForeignKey("RulesetId", "RulesetVersion").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SpellContentRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null).WithMany()
                        .HasForeignKey("RulesetId", "Version").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SpellPackRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null).WithMany()
                        .HasForeignKey("RulesetId", "RulesetVersion").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("DndEngine.Infrastructure.SkillRow", b =>
                {
                    b.HasOne("DndEngine.Infrastructure.RulesetRow", null)
                        .WithMany()
                        .HasForeignKey("RulesetId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
