<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DndEngine.Application\DndEngine.Application.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>
  <ItemGroup><EmbeddedResource Include="Content/skills-5.2.1.json" /><EmbeddedResource Include="Content/combat-5.2.1.json" /><EmbeddedResource Include="Content/monsters-5.2.1-pack1.json" /><EmbeddedResource Include="Content/items-5.2.1-pack1.json" /></ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
